blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://discord.com/channels/883083792112300104/962299008259342366
    about: Ask the community for help
  - name: Request a feature
    url: https://discord.com/channels/883083792112300104/962299008259342366
    about: Share ideas for new features
  - name: Report a security issue
    url: https://github.com/DutchCodingCompany/filament-socialite/security/policy
    about: Learn how to notify us for sensitive bugs
  - name: Report a bug
    url: https://github.com/DutchCodingCompany/filament-socialite/issues/new
    about: Report a reproducable bug
